/*
 * SWAPI
 * Welcome to the swapi, the Star Wars API! This documentation should help you familiarise yourself with the resources available and how to consume them with HTTP requests. If you're after a native helper library then I suggest you scroll down and check out what's available. Read through the getting started section before you dive in. Most of your problems should be solved just by reading through it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.sunflux.swapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Films
 */
@JsonPropertyOrder({
  Films.JSON_PROPERTY_TITLE,
  Films.JSON_PROPERTY_EPISODE_ID,
  Films.JSON_PROPERTY_OPENING_CRAWL,
  Films.JSON_PROPERTY_DIRECTOR,
  Films.JSON_PROPERTY_PRODUCER,
  Films.JSON_PROPERTY_STARSHIPS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-10-07T21:37:51.541+02:00[Europe/Belgrade]")
public class Films   {
  public static final String JSON_PROPERTY_TITLE = "title";
  @JsonProperty(JSON_PROPERTY_TITLE)
  private String title;

  public static final String JSON_PROPERTY_EPISODE_ID = "episode_id";
  @JsonProperty(JSON_PROPERTY_EPISODE_ID)
  private String episodeId;

  public static final String JSON_PROPERTY_OPENING_CRAWL = "opening_crawl";
  @JsonProperty(JSON_PROPERTY_OPENING_CRAWL)
  private String openingCrawl;

  public static final String JSON_PROPERTY_DIRECTOR = "director";
  @JsonProperty(JSON_PROPERTY_DIRECTOR)
  private String director;

  public static final String JSON_PROPERTY_PRODUCER = "producer";
  @JsonProperty(JSON_PROPERTY_PRODUCER)
  private String producer;

  public static final String JSON_PROPERTY_STARSHIPS = "starships";
  @JsonProperty(JSON_PROPERTY_STARSHIPS)
  private List<String> starships = null;

  public Films title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   **/
  @JsonProperty("title")
  @ApiModelProperty(value = "")
  
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Films episodeId(String episodeId) {
    this.episodeId = episodeId;
    return this;
  }

  /**
   * Get episodeId
   * @return episodeId
   **/
  @JsonProperty("episode_id")
  @ApiModelProperty(value = "")
  
  public String getEpisodeId() {
    return episodeId;
  }

  public void setEpisodeId(String episodeId) {
    this.episodeId = episodeId;
  }

  public Films openingCrawl(String openingCrawl) {
    this.openingCrawl = openingCrawl;
    return this;
  }

  /**
   * Get openingCrawl
   * @return openingCrawl
   **/
  @JsonProperty("opening_crawl")
  @ApiModelProperty(value = "")
  
  public String getOpeningCrawl() {
    return openingCrawl;
  }

  public void setOpeningCrawl(String openingCrawl) {
    this.openingCrawl = openingCrawl;
  }

  public Films director(String director) {
    this.director = director;
    return this;
  }

  /**
   * Get director
   * @return director
   **/
  @JsonProperty("director")
  @ApiModelProperty(value = "")
  
  public String getDirector() {
    return director;
  }

  public void setDirector(String director) {
    this.director = director;
  }

  public Films producer(String producer) {
    this.producer = producer;
    return this;
  }

  /**
   * Get producer
   * @return producer
   **/
  @JsonProperty("producer")
  @ApiModelProperty(value = "")
  
  public String getProducer() {
    return producer;
  }

  public void setProducer(String producer) {
    this.producer = producer;
  }

  public Films starships(List<String> starships) {
    this.starships = starships;
    return this;
  }

  public Films addStarshipsItem(String starshipsItem) {
    if (this.starships == null) {
      this.starships = new ArrayList<String>();
    }
    this.starships.add(starshipsItem);
    return this;
  }

  /**
   * An array of starship resource URLs that are in this film.
   * @return starships
   **/
  @JsonProperty("starships")
  @ApiModelProperty(value = "An array of starship resource URLs that are in this film.")
  
  public List<String> getStarships() {
    return starships;
  }

  public void setStarships(List<String> starships) {
    this.starships = starships;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Films films = (Films) o;
    return Objects.equals(this.title, films.title) &&
        Objects.equals(this.episodeId, films.episodeId) &&
        Objects.equals(this.openingCrawl, films.openingCrawl) &&
        Objects.equals(this.director, films.director) &&
        Objects.equals(this.producer, films.producer) &&
        Objects.equals(this.starships, films.starships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, episodeId, openingCrawl, director, producer, starships);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Films {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    episodeId: ").append(toIndentedString(episodeId)).append("\n");
    sb.append("    openingCrawl: ").append(toIndentedString(openingCrawl)).append("\n");
    sb.append("    director: ").append(toIndentedString(director)).append("\n");
    sb.append("    producer: ").append(toIndentedString(producer)).append("\n");
    sb.append("    starships: ").append(toIndentedString(starships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

