/*
 * SWAPI
 * Welcome to the swapi, the Star Wars API! This documentation should help you familiarise yourself with the resources available and how to consume them with HTTP requests. If you're after a native helper library then I suggest you scroll down and check out what's available. Read through the getting started section before you dive in. Most of your problems should be solved just by reading through it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.sunflux.swapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * People
 */
@JsonPropertyOrder({
  People.JSON_PROPERTY_NAME,
  People.JSON_PROPERTY_SKIN_COLOR,
  People.JSON_PROPERTY_BIRTH_YEAR,
  People.JSON_PROPERTY_EYE_COLOR,
  People.JSON_PROPERTY_GENDER,
  People.JSON_PROPERTY_HAIR_COLOR,
  People.JSON_PROPERTY_HEIGHT,
  People.JSON_PROPERTY_MASS,
  People.JSON_PROPERTY_URL,
  People.JSON_PROPERTY_CREATED,
  People.JSON_PROPERTY_EDITED,
  People.JSON_PROPERTY_HOMEWORLD,
  People.JSON_PROPERTY_FILMS,
  People.JSON_PROPERTY_SPECIES,
  People.JSON_PROPERTY_STARSHIPS,
  People.JSON_PROPERTY_VEHICLES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-10-07T23:20:46.085+02:00[Europe/Belgrade]")
public class People   {
  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_SKIN_COLOR = "skin_color";
  @JsonProperty(JSON_PROPERTY_SKIN_COLOR)
  private String skinColor;

  public static final String JSON_PROPERTY_BIRTH_YEAR = "birth_year";
  @JsonProperty(JSON_PROPERTY_BIRTH_YEAR)
  private String birthYear;

  public static final String JSON_PROPERTY_EYE_COLOR = "eye_color";
  @JsonProperty(JSON_PROPERTY_EYE_COLOR)
  private String eyeColor;

  public static final String JSON_PROPERTY_GENDER = "gender";
  @JsonProperty(JSON_PROPERTY_GENDER)
  private String gender;

  public static final String JSON_PROPERTY_HAIR_COLOR = "hair_color";
  @JsonProperty(JSON_PROPERTY_HAIR_COLOR)
  private String hairColor;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  private String height;

  public static final String JSON_PROPERTY_MASS = "mass";
  @JsonProperty(JSON_PROPERTY_MASS)
  private String mass;

  public static final String JSON_PROPERTY_URL = "url";
  @JsonProperty(JSON_PROPERTY_URL)
  private String url;

  public static final String JSON_PROPERTY_CREATED = "created";
  @JsonProperty(JSON_PROPERTY_CREATED)
  private Date created;

  public static final String JSON_PROPERTY_EDITED = "edited";
  @JsonProperty(JSON_PROPERTY_EDITED)
  private Date edited;

  public static final String JSON_PROPERTY_HOMEWORLD = "homeworld";
  @JsonProperty(JSON_PROPERTY_HOMEWORLD)
  private String homeworld;

  public static final String JSON_PROPERTY_FILMS = "films";
  @JsonProperty(JSON_PROPERTY_FILMS)
  private List<String> films = null;

  public static final String JSON_PROPERTY_SPECIES = "species";
  @JsonProperty(JSON_PROPERTY_SPECIES)
  private List<String> species = null;

  public static final String JSON_PROPERTY_STARSHIPS = "starships";
  @JsonProperty(JSON_PROPERTY_STARSHIPS)
  private List<String> starships = null;

  public static final String JSON_PROPERTY_VEHICLES = "vehicles";
  @JsonProperty(JSON_PROPERTY_VEHICLES)
  private List<String> vehicles = null;

  public People name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public People skinColor(String skinColor) {
    this.skinColor = skinColor;
    return this;
  }

  /**
   * Get skinColor
   * @return skinColor
   **/
  @JsonProperty("skin_color")
  @ApiModelProperty(value = "")
  
  public String getSkinColor() {
    return skinColor;
  }

  public void setSkinColor(String skinColor) {
    this.skinColor = skinColor;
  }

  public People birthYear(String birthYear) {
    this.birthYear = birthYear;
    return this;
  }

  /**
   * Get birthYear
   * @return birthYear
   **/
  @JsonProperty("birth_year")
  @ApiModelProperty(value = "")
  
  public String getBirthYear() {
    return birthYear;
  }

  public void setBirthYear(String birthYear) {
    this.birthYear = birthYear;
  }

  public People eyeColor(String eyeColor) {
    this.eyeColor = eyeColor;
    return this;
  }

  /**
   * Get eyeColor
   * @return eyeColor
   **/
  @JsonProperty("eye_color")
  @ApiModelProperty(value = "")
  
  public String getEyeColor() {
    return eyeColor;
  }

  public void setEyeColor(String eyeColor) {
    this.eyeColor = eyeColor;
  }

  public People gender(String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   * @return gender
   **/
  @JsonProperty("gender")
  @ApiModelProperty(value = "")
  
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public People hairColor(String hairColor) {
    this.hairColor = hairColor;
    return this;
  }

  /**
   * Get hairColor
   * @return hairColor
   **/
  @JsonProperty("hair_color")
  @ApiModelProperty(value = "")
  
  public String getHairColor() {
    return hairColor;
  }

  public void setHairColor(String hairColor) {
    this.hairColor = hairColor;
  }

  public People height(String height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   **/
  @JsonProperty("height")
  @ApiModelProperty(value = "")
  
  public String getHeight() {
    return height;
  }

  public void setHeight(String height) {
    this.height = height;
  }

  public People mass(String mass) {
    this.mass = mass;
    return this;
  }

  /**
   * Get mass
   * @return mass
   **/
  @JsonProperty("mass")
  @ApiModelProperty(value = "")
  
  public String getMass() {
    return mass;
  }

  public void setMass(String mass) {
    this.mass = mass;
  }

  public People url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   **/
  @JsonProperty("url")
  @ApiModelProperty(value = "")
  
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public People created(Date created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   **/
  @JsonProperty("created")
  @ApiModelProperty(value = "")
  
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public People edited(Date edited) {
    this.edited = edited;
    return this;
  }

  /**
   * Get edited
   * @return edited
   **/
  @JsonProperty("edited")
  @ApiModelProperty(value = "")
  
  public Date getEdited() {
    return edited;
  }

  public void setEdited(Date edited) {
    this.edited = edited;
  }

  public People homeworld(String homeworld) {
    this.homeworld = homeworld;
    return this;
  }

  /**
   * Get homeworld
   * @return homeworld
   **/
  @JsonProperty("homeworld")
  @ApiModelProperty(value = "")
  
  public String getHomeworld() {
    return homeworld;
  }

  public void setHomeworld(String homeworld) {
    this.homeworld = homeworld;
  }

  public People films(List<String> films) {
    this.films = films;
    return this;
  }

  public People addFilmsItem(String filmsItem) {
    if (this.films == null) {
      this.films = new ArrayList<String>();
    }
    this.films.add(filmsItem);
    return this;
  }

  /**
   * Get films
   * @return films
   **/
  @JsonProperty("films")
  @ApiModelProperty(value = "")
  
  public List<String> getFilms() {
    return films;
  }

  public void setFilms(List<String> films) {
    this.films = films;
  }

  public People species(List<String> species) {
    this.species = species;
    return this;
  }

  public People addSpeciesItem(String speciesItem) {
    if (this.species == null) {
      this.species = new ArrayList<String>();
    }
    this.species.add(speciesItem);
    return this;
  }

  /**
   * Get species
   * @return species
   **/
  @JsonProperty("species")
  @ApiModelProperty(value = "")
  
  public List<String> getSpecies() {
    return species;
  }

  public void setSpecies(List<String> species) {
    this.species = species;
  }

  public People starships(List<String> starships) {
    this.starships = starships;
    return this;
  }

  public People addStarshipsItem(String starshipsItem) {
    if (this.starships == null) {
      this.starships = new ArrayList<String>();
    }
    this.starships.add(starshipsItem);
    return this;
  }

  /**
   * Get starships
   * @return starships
   **/
  @JsonProperty("starships")
  @ApiModelProperty(value = "")
  
  public List<String> getStarships() {
    return starships;
  }

  public void setStarships(List<String> starships) {
    this.starships = starships;
  }

  public People vehicles(List<String> vehicles) {
    this.vehicles = vehicles;
    return this;
  }

  public People addVehiclesItem(String vehiclesItem) {
    if (this.vehicles == null) {
      this.vehicles = new ArrayList<String>();
    }
    this.vehicles.add(vehiclesItem);
    return this;
  }

  /**
   * Get vehicles
   * @return vehicles
   **/
  @JsonProperty("vehicles")
  @ApiModelProperty(value = "")
  
  public List<String> getVehicles() {
    return vehicles;
  }

  public void setVehicles(List<String> vehicles) {
    this.vehicles = vehicles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    People people = (People) o;
    return Objects.equals(this.name, people.name) &&
        Objects.equals(this.skinColor, people.skinColor) &&
        Objects.equals(this.birthYear, people.birthYear) &&
        Objects.equals(this.eyeColor, people.eyeColor) &&
        Objects.equals(this.gender, people.gender) &&
        Objects.equals(this.hairColor, people.hairColor) &&
        Objects.equals(this.height, people.height) &&
        Objects.equals(this.mass, people.mass) &&
        Objects.equals(this.url, people.url) &&
        Objects.equals(this.created, people.created) &&
        Objects.equals(this.edited, people.edited) &&
        Objects.equals(this.homeworld, people.homeworld) &&
        Objects.equals(this.films, people.films) &&
        Objects.equals(this.species, people.species) &&
        Objects.equals(this.starships, people.starships) &&
        Objects.equals(this.vehicles, people.vehicles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, skinColor, birthYear, eyeColor, gender, hairColor, height, mass, url, created, edited, homeworld, films, species, starships, vehicles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class People {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    skinColor: ").append(toIndentedString(skinColor)).append("\n");
    sb.append("    birthYear: ").append(toIndentedString(birthYear)).append("\n");
    sb.append("    eyeColor: ").append(toIndentedString(eyeColor)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    hairColor: ").append(toIndentedString(hairColor)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    mass: ").append(toIndentedString(mass)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    homeworld: ").append(toIndentedString(homeworld)).append("\n");
    sb.append("    films: ").append(toIndentedString(films)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    starships: ").append(toIndentedString(starships)).append("\n");
    sb.append("    vehicles: ").append(toIndentedString(vehicles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

