/*
 * SWAPI
 * Welcome to the swapi, the Star Wars API! This documentation should help you familiarise yourself with the resources available and how to consume them with HTTP requests. If you're after a native helper library then I suggest you scroll down and check out what's available. Read through the getting started section before you dive in. Most of your problems should be solved just by reading through it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.sunflux.swapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * People
 */
@JsonPropertyOrder({
  People.JSON_PROPERTY_NAME,
  People.JSON_PROPERTY_BIRTH_YEAR,
  People.JSON_PROPERTY_EYE_COLOR,
  People.JSON_PROPERTY_GENDER,
  People.JSON_PROPERTY_HAIR_COLOR,
  People.JSON_PROPERTY_HEIGHT,
  People.JSON_PROPERTY_MASS,
  People.JSON_PROPERTY_FILMS,
  People.JSON_PROPERTY_STARSHIPS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-10-07T21:37:51.541+02:00[Europe/Belgrade]")
public class People   {
  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_BIRTH_YEAR = "birth_year";
  @JsonProperty(JSON_PROPERTY_BIRTH_YEAR)
  private String birthYear;

  public static final String JSON_PROPERTY_EYE_COLOR = "eye_color";
  @JsonProperty(JSON_PROPERTY_EYE_COLOR)
  private String eyeColor;

  public static final String JSON_PROPERTY_GENDER = "gender";
  @JsonProperty(JSON_PROPERTY_GENDER)
  private String gender;

  public static final String JSON_PROPERTY_HAIR_COLOR = "hair_color";
  @JsonProperty(JSON_PROPERTY_HAIR_COLOR)
  private String hairColor;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  private String height;

  public static final String JSON_PROPERTY_MASS = "mass";
  @JsonProperty(JSON_PROPERTY_MASS)
  private String mass;

  public static final String JSON_PROPERTY_FILMS = "films";
  @JsonProperty(JSON_PROPERTY_FILMS)
  private List<String> films = null;

  public static final String JSON_PROPERTY_STARSHIPS = "starships";
  @JsonProperty(JSON_PROPERTY_STARSHIPS)
  private List<String> starships = null;

  public People name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public People birthYear(String birthYear) {
    this.birthYear = birthYear;
    return this;
  }

  /**
   * Get birthYear
   * @return birthYear
   **/
  @JsonProperty("birth_year")
  @ApiModelProperty(value = "")
  
  public String getBirthYear() {
    return birthYear;
  }

  public void setBirthYear(String birthYear) {
    this.birthYear = birthYear;
  }

  public People eyeColor(String eyeColor) {
    this.eyeColor = eyeColor;
    return this;
  }

  /**
   * Get eyeColor
   * @return eyeColor
   **/
  @JsonProperty("eye_color")
  @ApiModelProperty(value = "")
  
  public String getEyeColor() {
    return eyeColor;
  }

  public void setEyeColor(String eyeColor) {
    this.eyeColor = eyeColor;
  }

  public People gender(String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   * @return gender
   **/
  @JsonProperty("gender")
  @ApiModelProperty(value = "")
  
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public People hairColor(String hairColor) {
    this.hairColor = hairColor;
    return this;
  }

  /**
   * Get hairColor
   * @return hairColor
   **/
  @JsonProperty("hair_color")
  @ApiModelProperty(value = "")
  
  public String getHairColor() {
    return hairColor;
  }

  public void setHairColor(String hairColor) {
    this.hairColor = hairColor;
  }

  public People height(String height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   **/
  @JsonProperty("height")
  @ApiModelProperty(value = "")
  
  public String getHeight() {
    return height;
  }

  public void setHeight(String height) {
    this.height = height;
  }

  public People mass(String mass) {
    this.mass = mass;
    return this;
  }

  /**
   * Get mass
   * @return mass
   **/
  @JsonProperty("mass")
  @ApiModelProperty(value = "")
  
  public String getMass() {
    return mass;
  }

  public void setMass(String mass) {
    this.mass = mass;
  }

  public People films(List<String> films) {
    this.films = films;
    return this;
  }

  public People addFilmsItem(String filmsItem) {
    if (this.films == null) {
      this.films = new ArrayList<String>();
    }
    this.films.add(filmsItem);
    return this;
  }

  /**
   * Get films
   * @return films
   **/
  @JsonProperty("films")
  @ApiModelProperty(value = "")
  
  public List<String> getFilms() {
    return films;
  }

  public void setFilms(List<String> films) {
    this.films = films;
  }

  public People starships(List<String> starships) {
    this.starships = starships;
    return this;
  }

  public People addStarshipsItem(String starshipsItem) {
    if (this.starships == null) {
      this.starships = new ArrayList<String>();
    }
    this.starships.add(starshipsItem);
    return this;
  }

  /**
   * Get starships
   * @return starships
   **/
  @JsonProperty("starships")
  @ApiModelProperty(value = "")
  
  public List<String> getStarships() {
    return starships;
  }

  public void setStarships(List<String> starships) {
    this.starships = starships;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    People people = (People) o;
    return Objects.equals(this.name, people.name) &&
        Objects.equals(this.birthYear, people.birthYear) &&
        Objects.equals(this.eyeColor, people.eyeColor) &&
        Objects.equals(this.gender, people.gender) &&
        Objects.equals(this.hairColor, people.hairColor) &&
        Objects.equals(this.height, people.height) &&
        Objects.equals(this.mass, people.mass) &&
        Objects.equals(this.films, people.films) &&
        Objects.equals(this.starships, people.starships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, birthYear, eyeColor, gender, hairColor, height, mass, films, starships);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class People {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    birthYear: ").append(toIndentedString(birthYear)).append("\n");
    sb.append("    eyeColor: ").append(toIndentedString(eyeColor)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    hairColor: ").append(toIndentedString(hairColor)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    mass: ").append(toIndentedString(mass)).append("\n");
    sb.append("    films: ").append(toIndentedString(films)).append("\n");
    sb.append("    starships: ").append(toIndentedString(starships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

