/*
 * SWAPI
 * Welcome to the swapi, the Star Wars API! This documentation should help you familiarise yourself with the resources available and how to consume them with HTTP requests. If you're after a native helper library then I suggest you scroll down and check out what's available. Read through the getting started section before you dive in. Most of your problems should be solved just by reading through it. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pl.sunflux.swapi.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * StarShip
 */
@JsonPropertyOrder({
  StarShip.JSON_PROPERTY_NAME,
  StarShip.JSON_PROPERTY_MODEL,
  StarShip.JSON_PROPERTY_MANUFACTURER,
  StarShip.JSON_PROPERTY_COST_IN_CREDITS,
  StarShip.JSON_PROPERTY_LENGTH,
  StarShip.JSON_PROPERTY_MAX_ATMOSPHERING_SPEED,
  StarShip.JSON_PROPERTY_CREW,
  StarShip.JSON_PROPERTY_PASSENGERS,
  StarShip.JSON_PROPERTY_CARGO_CAPACITY,
  StarShip.JSON_PROPERTY_CONSUMABLES,
  StarShip.JSON_PROPERTY_HYPERDRIVE_RATING,
  StarShip.JSON_PROPERTY_M_G_L_T,
  StarShip.JSON_PROPERTY_FILMS,
  StarShip.JSON_PROPERTY_CREATED,
  StarShip.JSON_PROPERTY_EDITED,
  StarShip.JSON_PROPERTY_URL,
  StarShip.JSON_PROPERTY_PILOTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-10-07T23:20:46.085+02:00[Europe/Belgrade]")
public class StarShip   {
  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_MODEL = "model";
  @JsonProperty(JSON_PROPERTY_MODEL)
  private String model;

  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  private String manufacturer;

  public static final String JSON_PROPERTY_COST_IN_CREDITS = "cost_in_credits";
  @JsonProperty(JSON_PROPERTY_COST_IN_CREDITS)
  private String costInCredits;

  public static final String JSON_PROPERTY_LENGTH = "length";
  @JsonProperty(JSON_PROPERTY_LENGTH)
  private String length;

  public static final String JSON_PROPERTY_MAX_ATMOSPHERING_SPEED = "max_atmosphering_speed";
  @JsonProperty(JSON_PROPERTY_MAX_ATMOSPHERING_SPEED)
  private String maxAtmospheringSpeed;

  public static final String JSON_PROPERTY_CREW = "crew";
  @JsonProperty(JSON_PROPERTY_CREW)
  private String crew;

  public static final String JSON_PROPERTY_PASSENGERS = "passengers";
  @JsonProperty(JSON_PROPERTY_PASSENGERS)
  private String passengers;

  public static final String JSON_PROPERTY_CARGO_CAPACITY = "cargo_capacity";
  @JsonProperty(JSON_PROPERTY_CARGO_CAPACITY)
  private String cargoCapacity;

  public static final String JSON_PROPERTY_CONSUMABLES = "consumables";
  @JsonProperty(JSON_PROPERTY_CONSUMABLES)
  private String consumables;

  public static final String JSON_PROPERTY_HYPERDRIVE_RATING = "hyperdrive_rating";
  @JsonProperty(JSON_PROPERTY_HYPERDRIVE_RATING)
  private String hyperdriveRating;

  public static final String JSON_PROPERTY_M_G_L_T = "MGLT";
  @JsonProperty(JSON_PROPERTY_M_G_L_T)
  private String MGLT;

  public static final String JSON_PROPERTY_FILMS = "films";
  @JsonProperty(JSON_PROPERTY_FILMS)
  private List<String> films = null;

  public static final String JSON_PROPERTY_CREATED = "created";
  @JsonProperty(JSON_PROPERTY_CREATED)
  private Date created;

  public static final String JSON_PROPERTY_EDITED = "edited";
  @JsonProperty(JSON_PROPERTY_EDITED)
  private Date edited;

  public static final String JSON_PROPERTY_URL = "url";
  @JsonProperty(JSON_PROPERTY_URL)
  private String url;

  public static final String JSON_PROPERTY_PILOTS = "pilots";
  @JsonProperty(JSON_PROPERTY_PILOTS)
  private String pilots;

  public StarShip name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public StarShip model(String model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   **/
  @JsonProperty("model")
  @ApiModelProperty(value = "")
  
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public StarShip manufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * Get manufacturer
   * @return manufacturer
   **/
  @JsonProperty("manufacturer")
  @ApiModelProperty(value = "")
  
  public String getManufacturer() {
    return manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  public StarShip costInCredits(String costInCredits) {
    this.costInCredits = costInCredits;
    return this;
  }

  /**
   * Get costInCredits
   * @return costInCredits
   **/
  @JsonProperty("cost_in_credits")
  @ApiModelProperty(value = "")
  
  public String getCostInCredits() {
    return costInCredits;
  }

  public void setCostInCredits(String costInCredits) {
    this.costInCredits = costInCredits;
  }

  public StarShip length(String length) {
    this.length = length;
    return this;
  }

  /**
   * Get length
   * @return length
   **/
  @JsonProperty("length")
  @ApiModelProperty(value = "")
  
  public String getLength() {
    return length;
  }

  public void setLength(String length) {
    this.length = length;
  }

  public StarShip maxAtmospheringSpeed(String maxAtmospheringSpeed) {
    this.maxAtmospheringSpeed = maxAtmospheringSpeed;
    return this;
  }

  /**
   * Get maxAtmospheringSpeed
   * @return maxAtmospheringSpeed
   **/
  @JsonProperty("max_atmosphering_speed")
  @ApiModelProperty(value = "")
  
  public String getMaxAtmospheringSpeed() {
    return maxAtmospheringSpeed;
  }

  public void setMaxAtmospheringSpeed(String maxAtmospheringSpeed) {
    this.maxAtmospheringSpeed = maxAtmospheringSpeed;
  }

  public StarShip crew(String crew) {
    this.crew = crew;
    return this;
  }

  /**
   * Get crew
   * @return crew
   **/
  @JsonProperty("crew")
  @ApiModelProperty(value = "")
  
  public String getCrew() {
    return crew;
  }

  public void setCrew(String crew) {
    this.crew = crew;
  }

  public StarShip passengers(String passengers) {
    this.passengers = passengers;
    return this;
  }

  /**
   * Get passengers
   * @return passengers
   **/
  @JsonProperty("passengers")
  @ApiModelProperty(value = "")
  
  public String getPassengers() {
    return passengers;
  }

  public void setPassengers(String passengers) {
    this.passengers = passengers;
  }

  public StarShip cargoCapacity(String cargoCapacity) {
    this.cargoCapacity = cargoCapacity;
    return this;
  }

  /**
   * Get cargoCapacity
   * @return cargoCapacity
   **/
  @JsonProperty("cargo_capacity")
  @ApiModelProperty(value = "")
  
  public String getCargoCapacity() {
    return cargoCapacity;
  }

  public void setCargoCapacity(String cargoCapacity) {
    this.cargoCapacity = cargoCapacity;
  }

  public StarShip consumables(String consumables) {
    this.consumables = consumables;
    return this;
  }

  /**
   * Get consumables
   * @return consumables
   **/
  @JsonProperty("consumables")
  @ApiModelProperty(value = "")
  
  public String getConsumables() {
    return consumables;
  }

  public void setConsumables(String consumables) {
    this.consumables = consumables;
  }

  public StarShip hyperdriveRating(String hyperdriveRating) {
    this.hyperdriveRating = hyperdriveRating;
    return this;
  }

  /**
   * Get hyperdriveRating
   * @return hyperdriveRating
   **/
  @JsonProperty("hyperdrive_rating")
  @ApiModelProperty(value = "")
  
  public String getHyperdriveRating() {
    return hyperdriveRating;
  }

  public void setHyperdriveRating(String hyperdriveRating) {
    this.hyperdriveRating = hyperdriveRating;
  }

  public StarShip MGLT(String MGLT) {
    this.MGLT = MGLT;
    return this;
  }

  /**
   * Get MGLT
   * @return MGLT
   **/
  @JsonProperty("MGLT")
  @ApiModelProperty(value = "")
  
  public String getMGLT() {
    return MGLT;
  }

  public void setMGLT(String MGLT) {
    this.MGLT = MGLT;
  }

  public StarShip films(List<String> films) {
    this.films = films;
    return this;
  }

  public StarShip addFilmsItem(String filmsItem) {
    if (this.films == null) {
      this.films = new ArrayList<String>();
    }
    this.films.add(filmsItem);
    return this;
  }

  /**
   * Get films
   * @return films
   **/
  @JsonProperty("films")
  @ApiModelProperty(value = "")
  
  public List<String> getFilms() {
    return films;
  }

  public void setFilms(List<String> films) {
    this.films = films;
  }

  public StarShip created(Date created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   **/
  @JsonProperty("created")
  @ApiModelProperty(value = "")
  
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public StarShip edited(Date edited) {
    this.edited = edited;
    return this;
  }

  /**
   * Get edited
   * @return edited
   **/
  @JsonProperty("edited")
  @ApiModelProperty(value = "")
  
  public Date getEdited() {
    return edited;
  }

  public void setEdited(Date edited) {
    this.edited = edited;
  }

  public StarShip url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   **/
  @JsonProperty("url")
  @ApiModelProperty(value = "")
  
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public StarShip pilots(String pilots) {
    this.pilots = pilots;
    return this;
  }

  /**
   * Get pilots
   * @return pilots
   **/
  @JsonProperty("pilots")
  @ApiModelProperty(value = "")
  
  public String getPilots() {
    return pilots;
  }

  public void setPilots(String pilots) {
    this.pilots = pilots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StarShip starShip = (StarShip) o;
    return Objects.equals(this.name, starShip.name) &&
        Objects.equals(this.model, starShip.model) &&
        Objects.equals(this.manufacturer, starShip.manufacturer) &&
        Objects.equals(this.costInCredits, starShip.costInCredits) &&
        Objects.equals(this.length, starShip.length) &&
        Objects.equals(this.maxAtmospheringSpeed, starShip.maxAtmospheringSpeed) &&
        Objects.equals(this.crew, starShip.crew) &&
        Objects.equals(this.passengers, starShip.passengers) &&
        Objects.equals(this.cargoCapacity, starShip.cargoCapacity) &&
        Objects.equals(this.consumables, starShip.consumables) &&
        Objects.equals(this.hyperdriveRating, starShip.hyperdriveRating) &&
        Objects.equals(this.MGLT, starShip.MGLT) &&
        Objects.equals(this.films, starShip.films) &&
        Objects.equals(this.created, starShip.created) &&
        Objects.equals(this.edited, starShip.edited) &&
        Objects.equals(this.url, starShip.url) &&
        Objects.equals(this.pilots, starShip.pilots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, model, manufacturer, costInCredits, length, maxAtmospheringSpeed, crew, passengers, cargoCapacity, consumables, hyperdriveRating, MGLT, films, created, edited, url, pilots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StarShip {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    costInCredits: ").append(toIndentedString(costInCredits)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    maxAtmospheringSpeed: ").append(toIndentedString(maxAtmospheringSpeed)).append("\n");
    sb.append("    crew: ").append(toIndentedString(crew)).append("\n");
    sb.append("    passengers: ").append(toIndentedString(passengers)).append("\n");
    sb.append("    cargoCapacity: ").append(toIndentedString(cargoCapacity)).append("\n");
    sb.append("    consumables: ").append(toIndentedString(consumables)).append("\n");
    sb.append("    hyperdriveRating: ").append(toIndentedString(hyperdriveRating)).append("\n");
    sb.append("    MGLT: ").append(toIndentedString(MGLT)).append("\n");
    sb.append("    films: ").append(toIndentedString(films)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    pilots: ").append(toIndentedString(pilots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

