swagger: '2.0'
info:
  description: |
    Welcome to the swapi, the Star Wars API! This documentation should help you familiarise yourself with the resources available and how to consume them with HTTP requests. If you're after a native helper library then I suggest you scroll down and check out what's available. Read through the getting started section before you dive in. Most of your problems should be solved just by reading through it.
  version: 1.0.0
  title: SWAPI
tags:
- name: people
  description: A People resource is an individual person or character within the Star Wars universe.
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: films
  description: A Film resource is a single film.
- name: starships
  description: A Starship resource is a single transport craft that has hyperdrive capability.
# schemes:
# - http
paths:
  /people:
    get:
      tags:
      - people
      summary: Get all the people resources
      operationId: showPeople
      produces:
      - application/json
      parameters:
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/People'
        400:
          description: Invalid ID supplied
        404:
          description: person not found
  /people/{peopleId}:
    get:
      tags:
      - people
      summary: Get a specific people resource
      description: Returns a single people
      produces:
      - application/json
      parameters:
      - name: peopleId
        in: path
        description: ID of person to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/People'
        400:
          description: Invalid ID supplied
        404:
          description: person not found
      security:
      - api_key: []
  /films:
    get:
      tags:
      - films
      summary: Get all the film resources
      operationId: showFilms
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Films'
  /films/{filmId}:
    get:
      tags:
      - films
      summary: get a specific film resource
      description: Returns a specific film
      operationId: getFilmById
      produces:
      - application/json
      parameters:
      - name: filmId
        in: path
        description: ID of film that needs to be fetched
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Films'
        400:
          description: Invalid ID supplied
        404:
          description: Order not found
  /starships/{starshipId}:
    get:
      tags:
      - starships
      summary: Get starship by its id
      operationId: getUserById
      produces:
      - application/json
      - application/xml
      parameters:
      - name: starshipId
        in: path
        description: The name that needs to be fetched. Use user1 for testing.
        required: true
        type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/StarShip'
        400:
          description: Invalid username supplied
        404:
          description: User not found
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  People:
    type: object
    properties:
      name:
        type: string
      birth_year:
        type: string
      eye_color:
        type: string
      gender:
        type: string
      hair_color:
        type: string
      height:
        type: string
      mass:
        type: string
      films:
        type: array
        items:
          type: string
      starships:
        type: array
        items:
          type: string
  StarShip:
    type: object
    properties:
      name:
        type: string
      model:
        type: string
      manufacturer:
        type: string
      cost_in_credits:
        type: string
      length:
        type: string
      max_atmosphering_speed:
        type: string
      crew:
        type: string
      passengers:
        type: string
      cargo_capacity:
        type: string
      consumables:
        type: string
      hyperdrive_rating:
        type: string
      MGLT:
        type: string
      films:
        type: array
        items:
          type: string
      created:
        type: string
        format: date-time
      edited:
        type: string
        format: date-time
      url:
        type: string
      pilots:
        type: string
  Planet:
    type: object
    properties:
      name:
        type: string
      rotation_period:
        type: string
      orbital_period:
        type: string
      diameter:
        type: string
      climate:
        type: string
      terrain:
        type: string
      surface_water:
        type: string
      population:
        type: string
      residents:
        type: array
        items:
          type: string
      films:
        type: array
        items:
          type: string
      created:
        type: string
        format: date-time
      edited:
        type: string
        format: date-time
      gravity:
        type: string
      url:
        type: string
  Films:
    type: object
    properties:
      title:
        type: string
      episode_id:
        type: string
      opening_crawl:
        type: string
      director:
        type: string
      producer:
        type: string
      starships:
        type: array
        description: An array of starship resource URLs that are in this film.
        items:
          type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

schemes:
- https
- http
# Added by API Auto Mocking Plugin
# host: swapi.co/api/
# Added by API Auto Mocking Plugin
# host: swapi.co/api/
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /ahardia/swapi/1.0.0